emit:
  - "@typespec/json-schema"
  - "@typespec/openapi3"
  - "@wavenumber/wn-contract-catalog-emitter"

options:
  "@typespec/json-schema":
    emitter-output-dir: "{output-dir}/schema"
    file-type: json
    int64-strategy: number
    emitAllModels: true
    emitAllRefs: true
    seal-object-schemas: true
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}"
    output-file: openapi.json
    file-type: json
    openapi-versions:
      - "3.1.0"
    omit-unreachable-types: false
    seal-object-schemas: true
  "@wavenumber/wn-contract-catalog-emitter":
    emitter-output-dir: "{output-dir}"

warn-as-error: true
