[package]
name = "supply-chain-monkey-client"
description = "Async client for the Supply Chain Monkey API"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
include = ["src/**/*.rs", "LICENSE", "README.md"]

[lib]
name = "scm_client"

[dependencies]
futures-util.workspace = true
reqwest.workspace = true
scm-contracts = { package = "supply-chain-monkey-contracts", path = "../scm-contracts", version = "=0.1.0" }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
axum.workspace = true
axum-server.workspace = true
rcgen.workspace = true
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
