[package]
name = "supply-chain-monkey-cli"
description = "Command-line client for Supply Chain Monkey"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
include = ["src/**/*.rs", "LICENSE", "README.md"]

[dependencies]
clap.workspace = true
scm-client = { package = "supply-chain-monkey-client", path = "../scm-client", version = "=0.1.0" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
axum.workspace = true

[[bin]]
name = "scm"
path = "src/main.rs"

[lints]
workspace = true
